#ifndef _CONFIG_H
#define _CONFIG_H

// Heaters relay config
#define RELAY_OUTPUT_PORT GPIOB
#define RELAY_OUTPUT_PIN GPIO6
#define RELAY_RCC_BIT RCC_GPIOB

// Temperatur sensor one wire config
#define ONE_WIRE_READ_PORT GPIOB
#define ONE_WIRE_READ_PIN GPIO7
#define ONE_WIRE_READ_RCC_BIT RCC_GPIOB

#define ONE_WIRE_WRITE_PORT GPIOB
#define ONE_WIRE_WRITE_PIN GPIO8
#define ONE_WIRE_WRITE_RCC_BIT RCC_GPIOB

#define ONE_WIRE_WRITE_TIMER_RCC RCC_TIM4
#define ONE_WIRE_WRITE_TIMER_RST RST_TIM4
#define ONE_WIRE_WRITE_TIMER TIM4
#define ONE_WIRE_WRITE_TIMER_OC TIM_OC3
#define ONE_WIRE_WRITE_TIMER_CCIF TIM_SR_CC3IF

#define TEMP_MAX 230

// User interface config
#define STATUS_LED_RCC_BIT RCC_GPIOA
#define STATUS_LED_PORT GPIOA
#define STATUS_LED_PIN GPIO8

#define BTN_RCC_BIT RCC_GPIOB
#define BTN_PORT GPIOB
#define BTN_PIN GPIO15

#endif
